version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_dev
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_dev
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://user:password@mongodb:27017/
    depends_on:
      - mongodb

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: obscure-openobserve
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: admin@example.com
      ZO_ROOT_USER_PASSWORD: Complexpass#123
      ZO_DATA_DIR: /data
    ports:
      - "5080:5080"
    volumes:
      - openobserve_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5080/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongo_data:
  openobserve_data:
